import asyncio
import json
import ssl
import urllib.error
import urllib.request

from app.models.analysis import OfferAnalysis
from app.models.negotiation import NegotiationResult
from app.models.offer import NegotiateRequest

try:
    import anthropic
    _ANTHROPIC_AVAILABLE = True
except ImportError:
    _ANTHROPIC_AVAILABLE = False

_MODEL = "claude-sonnet-4-6"
_MAX_TOKENS = 2048

SYSTEM_PROMPT = """You are an expert salary negotiation coach specializing in \
technology and professional roles. You have deep knowledge of compensation \
benchmarks, negotiation psychology, and employer hiring practices.

Your role is to:
1. Analyze a job offer in context of market data and any competing offers
2. Recommend a specific, defensible counter-offer amount with clear reasoning
3. Write a professional, non-confrontational negotiation email using the candidate's real numbers
4. Provide tactical talking points for a follow-up phone conversation

Rules:
- Always cite the exact market percentile and salary figures from the data provided
- Never use vague phrases like "industry standard" — use the actual numbers
- The email must sound human, not like it was generated by AI
- Floor should be 3-5% above the current offer; recommended counter should be 8-15% above \
(or higher if below market median)
- If a competing offer exists, use it as primary leverage
"""

_TOOL_SCHEMA = {
    "name": "generate_negotiation_script",
    "description": "Generate a structured salary negotiation script",
    "input_schema": {
        "type": "object",
        "properties": {
            "recommended_counter": {
                "type": "number",
                "description": "Recommended counter-offer base salary in USD"
            },
            "floor": {
                "type": "number",
                "description": "Minimum acceptable salary — walk away below this"
            },
            "stretch_goal": {
                "type": "number",
                "description": "Best-case ask if leverage is strong"
            },
            "email_subject": {"type": "string"},
            "email_body": {
                "type": "string",
                "description": "Full professional email body, 3-4 paragraphs"
            },
            "talking_points": {
                "type": "array",
                "items": {"type": "string"},
                "description": "4-6 bullet points for the phone conversation"
            },
            "leverage_notes": {
                "type": "string",
                "description": "Brief explanation of the candidate's key leverage points"
            },
        },
        "required": [
            "recommended_counter", "floor", "stretch_goal",
            "email_subject", "email_body", "talking_points", "leverage_notes"
        ],
    },
}


class NegotiatorService:

    def __init__(self, api_key: str = ""):
        self.api_key = api_key

    def build_prompt(
        self,
        request: NegotiateRequest,
        analysis: OfferAnalysis,
    ) -> str:
        offer = request.offer
        tc = analysis.total_comp
        benchmark = analysis.market_benchmark
        health = analysis.company_health

        lines = [
            "Analyze this job offer and generate a negotiation script.\n",
            "OFFER DETAILS:",
            f"  Company:       {offer.company_name}",
            f"  Role:          {offer.role}" + (f", {offer.level}" if offer.level else ""),
            f"  Location:      {offer.location}",
            f"  Base Salary:   ${offer.base_salary:,.0f}",
            f"  Signing Bonus: ${offer.signing_bonus or 0:,.0f}",
            f"  Bonus Target:  {offer.annual_bonus_target_pct or 0}% of base",
            f"  Total Comp:    ${tc.total:,.0f}/yr "
            f"  (base ${tc.base_salary:,.0f} + equity ${tc.equity_annualized:,.0f})",
        ]

        if benchmark:
            pct = f"{benchmark.your_percentile:.0f}th" if benchmark.your_percentile else "unknown"
            lines += [
                "\nMARKET DATA (BLS Occupational Employment Statistics):",
                f"  25th pct: ${benchmark.p25:,.0f}",
                f"  Median:   ${benchmark.p50:,.0f}",
                f"  75th pct: ${benchmark.p75:,.0f}",
                f"  Offered salary is at the {pct} percentile.",
            ]

        if analysis.col_adjusted_base:
            lines.append(
                f"\n  COL-adjusted purchasing power: "
                f"${analysis.col_adjusted_base:,.0f} (national avg equivalent)"
            )

        if health:
            lines += [
                "\nCOMPANY HEALTH:",
                f"  Risk level:    {health.layoff_risk}",
                f"  Notes:         {health.notes or 'N/A'}",
            ]

        lines.append(f"\nOFFER SCORE: {analysis.score:.0f}/100")

        if request.competing_offer:
            c = request.competing_offer
            lines += [
                "\nCOMPETING OFFER (use as leverage):",
                f"  {c.company_name}: ${c.base_salary:,.0f} base",
            ]

        if request.target_salary:
            lines.append(f"\nCANDIDATE'S TARGET: ${request.target_salary:,.0f}")

        if request.years_of_experience is not None:
            lines.append(f"\nYEARS OF EXPERIENCE: {request.years_of_experience}")

        lines.append("\nGenerate a specific, data-backed negotiation strategy.")
        return "\n".join(lines)

    # ── Response parsers ──────────────────────────────────────────────────────

    def _parse_tool_response(self, response) -> NegotiationResult:
        """Parse SDK response object (has .content with typed blocks)."""
        for block in response.content:
            if block.type == "tool_use" and block.name == "generate_negotiation_script":
                return NegotiationResult(**block.input)
        raise ValueError("Claude did not call the expected tool")

    def _parse_raw_response(self, raw: dict) -> NegotiationResult:
        """Parse raw dict response from Floodgate urllib call."""
        for block in raw.get("content", []):
            if block.get("type") == "tool_use" and \
               block.get("name") == "generate_negotiation_script":
                return NegotiationResult(**block["input"])
        raise ValueError("Claude did not call the expected tool")

    # ── Transports ────────────────────────────────────────────────────────────

    async def _call_anthropic_sdk(self, prompt: str) -> NegotiationResult:
        if not _ANTHROPIC_AVAILABLE:
            raise RuntimeError(
                "anthropic package is not installed. "
                "Run: pip install anthropic"
            )
        client = anthropic.Anthropic(api_key=self.api_key)
        response = client.messages.create(
            model=_MODEL,
            max_tokens=_MAX_TOKENS,
            system=[
                {
                    "type": "text",
                    "text": SYSTEM_PROMPT,
                    "cache_control": {"type": "ephemeral"},
                }
            ],
            tools=[_TOOL_SCHEMA],
            tool_choice={"type": "tool", "name": "generate_negotiation_script"},
            messages=[{"role": "user", "content": prompt}],
        )
        return self._parse_tool_response(response)

    async def _call_floodgate(self, prompt: str) -> NegotiationResult:
        """Apple-internal Floodgate transport — mTLS via urllib, zero extra deps."""
        from app.config import settings

        url = settings.floodgate_url
        if not url:
            raise RuntimeError(
                "FLOODGATE_URL is not set. Add it to .env or set it as an environment variable."
            )

        def _sync_request():
            ctx = ssl.create_default_context()
            ctx.load_cert_chain(certfile=settings.floodgate_cert, keyfile=settings.floodgate_key)

            payload = json.dumps({
                "model": f"anthropic.{_MODEL}",
                "max_tokens": _MAX_TOKENS,
                "system": SYSTEM_PROMPT,
                "tools": [_TOOL_SCHEMA],
                "tool_choice": {"type": "tool", "name": "generate_negotiation_script"},
                "messages": [{"role": "user", "content": prompt}],
            }).encode()

            req = urllib.request.Request(
                url,
                data=payload,
                headers={
                    "anthropic-version": "2023-06-01",
                    "content-type": "application/json",
                },
                method="POST",
            )
            with urllib.request.urlopen(req, context=ctx) as resp:
                return json.loads(resp.read())

        try:
            raw = await asyncio.to_thread(_sync_request)
        except urllib.error.HTTPError as e:
            raise RuntimeError(f"Floodgate API error {e.code}: {e.read().decode()}")
        except Exception as e:
            raise RuntimeError(f"Floodgate request failed: {e}")

        return self._parse_raw_response(raw)

    # ── Public entry point ────────────────────────────────────────────────────

    async def _call_claude(self, prompt: str) -> NegotiationResult:
        """Auto-selects Floodgate if certs are configured, else Anthropic SDK."""
        from app.config import settings
        if settings.floodgate_cert and settings.floodgate_key:
            return await self._call_floodgate(prompt)
        return await self._call_anthropic_sdk(prompt)

    async def get_script(
        self,
        request: NegotiateRequest,
        analysis: OfferAnalysis,
    ) -> NegotiationResult:
        prompt = self.build_prompt(request, analysis)
        return await self._call_claude(prompt)
